### ISSUE TITLE
BaselineOfPunQLite doesn't complete in systems that doesn't support 32 bits anymore

### ISSUE THREAD

**Issue by sebastianconcept** [mumez/PunQLite#2]
I needed to make the baseline to **not** execute its preload and compile the unqlite library locally to make it work. All good after that.

**Comment by mumez** [comment]
Downloading appropriate pre-built binary is getting hard because of the variety of platforms (such as ARM or Intel, 32 bit or 64 bit).
So I think it is good to remove the preload script. 

PunQLite is now mainly maintained in the forked repositoty. So, I would appreciate if you could post the PR here as well:
https://github.com/pharo-nosql/PunQLite
